version: "3.7"

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.spacy
    image: spacy
    container_name: spacy
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - "./work:/home/work"
      - ".jupyter:/root/.jupyter"
    ports:
    - "8080:8080"
    tty: true
    command: jupyter lab --ip=0.0.0.0 --port=8080 --allow-root --NotebookApp.token='' --no-browser